### ISSUE TITLE
In CI, check if all imported libraries are defined explicitly in our dependencies

### ISSUE THREAD

**Issue by thomass-dev** [probabl-ai/skore#405]
We must ensure that installing skore is reproductible.
Unittests are not sufficient because imported libraries can be shipped by one of our third-party libraries.

**Comment by augustebaum** [comment]
Check out https://github.com/tweag/FawltyDeps

**Comment by tuscland** [comment]
As long as the benefit/maintainability balance is positive, this is nice to have.

**Comment by augustebaum** [comment]
## Status update as of commit 2cba652

```
$ fawltydeps --detailed

These imports appear to be undeclared dependencies:
- 'IPython' imported at:
    src/skore/cross_validate.py:253
- 'hatchling' imported at:
    hatch/metadata.py:4
- 'numpy' imported at:
    src/skore/item/cross_validation_item.py:13
    src/skore/item/numpy_array_item.py:12
    src/skore/item/numpy_array_item.py:72
    src/skore/item/numpy_array_item.py:91
    tests/integration/test_cross_validate.py:1
    tests/integration/test_cross_validate.py:5
    tests/unit/item/test_cross_validation_item.py:1
    tests/unit/item/test_numpy_array_item.py:1
    tests/unit/test_project.py:5
    tests/unit/test_project.py:6
- 'starlette' imported at:
    src/skore/ui/app.py:8

These dependencies appear to be unused (i.e. not imported):
- 'httpx' declared in:
    pyproject.toml
- 'pytest-cov' declared in:
    pyproject.toml
- 'pytest-order' declared in:
    pyproject.toml
- 'pytest-randomly' declared in:
    pyproject.toml
```

- `IPython`: this is because we run IPython's `display` method. We run it only when it's available (e.g. in a notebook), so we can ignore this.
- `hatchling`: we only need this when we release, so we can ignore it.
- `numpy`: this one is more concerning; we should either add numpy to our direct dependencies or refactor the code that computes the hash of numpy arrays during the cross-validation process. I'll open an issue.
- `starlette`: this is just for a type annotation, and it's a dependency of FastAPI, so not sure what to do.
- `httpx`: indeed I don't think we use it currently, and I think it's a dependency of FastAPI? I'll try to remove it I guess.
- `pytest-.*`: I don't remember if `pytest-order` is used currently, but through pytest's mark system, which fawltydeps isn't smart enough to tell; the others are there for a reason.

Also of note: I just realized that I did not add `scikit-learn` to the dependencies, even though it is required for cross-validation, but fawltydeps didn't detect this. Currently the imports are done locally (within the functions), but even when I move the imports outside of the functions it still doesn't detect it.
I wonder if I should add it...

**Comment by augustebaum** [comment]
I'm not sure this is actionable, as evidenced by the limitations with fawltydeps for example. I think we can think about this again when the issue arises for real.
