### ISSUE TITLE
Add windows support

### ISSUE THREAD

**Issue by augustebaum** [probabl-ai/skore#475]
### Is your feature request related to a problem? Please describe.

We have no idea whether skore works for users on Windows, which constitute a large number of potential users. We should make sure that it does work, or at least make it clear whether we support yet it or not.

### Describe the solution you'd like

A good first step would be to run tests in CI on Windows machines as well as Linux.

**Comment by BastienGauthier** [comment]
Hello ! For your info, I just tried to install skore on Windows, and I add a small issue at the initialisation, after

`python -m skore create 'project.skore'`

![image](https://github.com/user-attachments/assets/dcfc22e1-0541-4e89-b58e-4a191c07a3de)

This is solved by removing the quotes. Moreover, I find the ImproperProjectName error not perfectly clear due to the ".skore" automatically integrated. (this may be only a matter of habits, I just started using it)

**Comment by tuscland** [comment]
Hi Bastien,

Thank you for your feedback!
Very happy to have you as a user.

> I find the ImproperProjectName error not perfectly clear due to the ".skore" automatically integrated.

Could you please elaborate a bit on this?

Side note to @thomass-dev: I suggest `ImproperProjectName` should be named `InvalidProjectName`.

**Comment by BastienGauthier** [comment]
To precise, I wanted to highlight that the project name is said to contain alphanumeric, '_' and '-' caracters, but the example has a '.'. Even if this is perfectly normal given it is a predefined suffix, the error along the example can be misleading. Maybe in the ReadMe something like :
`python -m skore create project_example`
may be clearer ?

**Comment by tuscland** [comment]
The project name is defined to be the part before the extension. Now I understand why the error message could be misleading, thank you for the clarification. We will update the docs as suggested.
