### ISSUE TITLE
Overwriting an item with an item from a different type should raise a warning

### ISSUE THREAD

**Issue by sylvaincom** [probabl-ai/skore#513]
### Is your feature request related to a problem? Please describe.

```python
from skore import load
project = load("project.skore")
project.put("my_int", 3)
project.put("my_int", "hello")
```
this code snippet does not return any warning. I can overwrite an integer with a string: maybe I overwrote by mistake, and that would make me lose my first variable!

### Describe the solution you'd like

If I overwrite an item with an item of different type, I would to have to confirm before it overwrites my previously stored item (should raise a warning).

For example, overwriting a plot by an integer or the results of my cross validation by a string must have been an error (as the user, I forgot the item name is already taken for example) that would make me loose all the results from my cross validation that took a long time to compute.

**Comment by tuscland** [comment]
Note: this suggestion came from a user feedback.

I understand it is suggested to raise an exception if the type changes. What is interesting in your example is that the item type did not change: it is still a primitive item.

So, what would be the threshold in order to detect a change in type? I suggest that the value of the item type is compared, not the item type itself. That means we accept to replace a dictionary with another. And here I find the feature lacks consistency.

Going back to the requirement: _I don't want to lose the results from my cross validation that took a long time to compute_. 
- This pain point has also been expressed in #14. The latter concluded that it is the responsibility of the user to take care of not overwriting items.
- Curiously, the resulting feature bears the same complications as in #389. Where does the user's responsibility starts, and where does it end?

The initial requirement has some validity.

If all updates to an item are saved, we no longer care about an information being overwritten.

Closing in favor of keeping some responsibility on the user side, and hoping #504 and #403 will help.
