### ISSUE TITLE
UI: Display a warning when the user tries to add an item already in the view

### ISSUE THREAD

**Issue by MarieS-WiMLDS** [probabl-ai/skore#570]
### Is your feature request related to a problem? Please describe.

I'm frustrated when I click on the "plus" of an item and nothing happens because the item is already in the view. I'm confused because I suspect a bug first. 

### Describe the solution you'd like

I'd like to have a toaster like the others we have when displaying a warning to say  `you've already added this item`.  

### Describe alternatives you've considered, if relevant

Allowing to display several times the same item.

**Comment by anasstarfaoui** [comment]
Hey there! Thanks for reporting this frustration with the "+" button. While indeed, adding a toast message can give users some feedback, I think we need to take a step back and look at the bigger picture, trying to solve root problem.

Right now, when you click "+" and nothing happens, it feels broken – and that's not great UX. Instead of just telling users "this is already here," we should make the whole interaction more intuitive.

Here are a few ideas we could explore:

- What if new elements always appeared at the top of the canvas? That way, you'd immediately see something happen when clicking "+"

- We could highlight existing instances when you try to add a duplicate – kind of like how browsers flash a tab when you try to open a page that's already open

- The "+" button itself could be smarter – maybe showing a different state when that element is already on the canvas

- We could also show with an indicator on elements how many instances of the same element we have on the page

Before we implement any solution though, we should probably answer a key question: do we actually want to allow multiple instances of the same element? This would help us decide whether to:

Make it super clear when something's already there and prevent duplicates
Make it easier to see and manage multiple instances of the same element

What are your thoughts on this? Happy to dive deeper into any of these approaches

**Comment by MarieS-WiMLDS** [comment]
I really like the idea of `highlighting existing instances when you try to add a duplicate – kind of like how browsers flash a tab when you try to open a page that's already open`! Because it's useful when the view is a bit crowded (which can come quickly, in 3 plots the window is already full, and you have to scroll to see everything). It's also the reason why I don't think appearing at the top is a solution: if the item already added is at the bottom of the view, then you don't see it either.  
I also feel that highlighting existing instances will be useful even if we allow duplicates. Saying "this item already appears 3 times in the view" is interesting, maybe I'll wonder if I really need to add it a fourth time.  

Finally, fully aligned on the first question: `do we actually want to allow multiple instances of the same element?`. And I have no clue what opinion would be best for now!

**Comment by anasstarfaoui** [comment]
Okay so, do you think we should take a little time on research to decide the best option or should we try to implement a quick fix, then change it later ?

**Comment by MarieS-WiMLDS** [comment]
We can spend some time on research, all the more that we might allow several items in a view, making this issue irrelevant.

**Comment by anasstarfaoui** [comment]
For now, here is a proposition to showcase the user there is a problem when adding an element already in view.

Drag an element -> When element is released in the landing area, the are turn red and a toast appears to explain that there is a problem with this element 
![image](https://github.com/user-attachments/assets/51336f22-8e3e-4e19-bd1a-05fe787efed5)

**Comment by MarieS-WiMLDS** [comment]
I like this solution!  
How would we do about the "plus" button? It could be grayed out? Plus the toast as for the drag an drop?

**Comment by anasstarfaoui** [comment]
It will be the same principle so you can try to add, but after hit the plus button it should return an error message, like in the initial screen (so we can keep the same pattern of permitting user to try to add the element and after that display the error)

**Comment by rouk1** [comment]
My 2 cents : disabling drag'n'drop and the plus button for already added item is way more easy to implement and maintain that to present an error after interaction as been done.

**Comment by anasstarfaoui** [comment]
I'm okay with that, we just need to figure out how to give the info of an already place item
+ 
It's only a temporary solution until we can explore exactly how users interact with this pattern

**Comment by tuscland** [comment]
Decision is to implement Matt's suggestion:
> disabling drag'n'drop and the plus button for already added item is way more easy to implement and maintain that to present an error after interaction as been done.
