### ISSUE TITLE
Enhance `skore.cross_validate`: add the train score

### ISSUE THREAD

**Issue by sylvaincom** [probabl-ai/skore#579]
### Problem

Part of epic https://github.com/probabl-ai/skore/issues/544

Currently, we do not plot the train score, which is important to visualize to understand what is going on between each split.

### Suggested solution

Include the train score in the plots.
A nice display would be to compare, for each split, the train and test scores stacked in bar plots (same a comparing the train and test times stacked in bar plots).

**Comment by augustebaum** [comment]
This is not hard to do, but note that according to the [sklearn docs](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_validate.html):
> computing the scores on the training set can be computationally expensive and is not strictly required

There is a balance to be found when computing stuff before the user asks for it, especially when the data is large.

sklearn's cross_validate accepts a `return_train_score` argument, so we could do something where we compute it by default, but if the user runs `skore.cross_validate` with `return_train_score=False` we turn it off --- making it opt-out rather than opt-in.

**Comment by sylvaincom** [comment]
Hmm maybe we could try automatically computing the training score with a timeout?

**Comment by augustebaum** [comment]
Sure, what timeout duration would be appropriate?

**Comment by sylvaincom** [comment]
5 seconds? cc @MarieS-WiMLDS

**Comment by MarieS-WiMLDS** [comment]
I'd rather not do it. There is an option in cross_validate (return train score), if the user is interested in it, they can do it without us. Having a timeout also feels not so reliable and somehow messy, because we will have to explain to users why sometimes it appears, and why sometimes it doesn't.

**Comment by koaning** [comment]
Timeout is indeed not a great idea. Having a `return_train_score` would totally suffice on my end because it is a standard across sklearn, also in the [GridSearchCV](https://scikit-learn.org/dev/modules/generated/sklearn.model_selection.GridSearchCV.html) just to name one example.

**Comment by koaning** [comment]
Ah! Right, because of the `**kwargs`. I guess this was not clear because it was not listed directly in the docstring. Might be nice to mention the kwargs explicitly to avoid confusion.
Or actually ... why not make them normal arguments/keyword arguments? That feels most explicit. 

But yeah, I would mimic the same default so `return_train_score=False` per default just like sklearn.

**Comment by tuscland** [comment]
@sylvaincom the parent issue is closed, but this one is still open. That reveals a workflow issue, can you please check?

**Comment by sylvaincom** [comment]
This can be closed because we have `return_train_score=True `
