### ISSUE TITLE
docs: improvements following feedbacks

### ISSUE THREAD

**Issue by MarieS-WiMLDS** [probabl-ai/skore#588]
# context

First release of the docs, we had a lot of feedback. Let's concatenate all of them here. 

# TODO

- [x] #592
- [x] #593
- [x] #589
- [x] #590
- [x] #591
- [x] #594
- [x] #595

**Comment by augustebaum** [comment]
Why is this an epic? Now that everything has been converted to issues, can this issue be closed?

**Comment by augustebaum** [comment]
Ah, so it was marked as "epic" specifically because we don't want it to pollute; that's fine, thanks for explaining.

I don't think it's overkill, especially because I know that writing one big issue is much easier than many little ones. I'm just wary that issues like these are never-ending, and I generally like closing issues.

**Comment by MarieS-WiMLDS** [comment]
> issues like these are never-ending  
It's definitely something that we will have to monitor so we don't end up with a huge list of epics!

**Comment by sylvaincom** [comment]
https://github.com/probabl-ai/skore/pull/611 fixed most of these issues, the reste is WIP

**Comment by sylvaincom** [comment]
Should we close this issue in favor of https://github.com/probabl-ai/skore/issues/627? cc @MarieS-WiMLDS

**Comment by MarieS-WiMLDS** [comment]
Can't we finish the last task before closing this issue? (the plotly graph one) It's not a huge issue, and Auguste is already working on it.

**Comment by sylvaincom** [comment]
Sure

**Comment by MarieS-WiMLDS** [comment]
all tasks are done --> we can close.
