### ISSUE TITLE
fix(docs): Improve the contributing link

### ISSUE THREAD

**Issue by sylvaincom** [probabl-ai/skore#642]
> I guess that also works, but I expected the CONTRIBUTING.md to just be shortened to something like:
>```
>To contribute, take a look at the docs at <http://skore/docs/contributing>
>```
>, not to be a mirror of the online docs. If you considered this option, can you explain why you did it >differently? Otherwise just resolve, it's fine

_Originally posted by @augustebaum in https://github.com/probabl-ai/skore/pull/636#discussion_r1822772059_

**Comment by augustebaum** [comment]
There was a misunderstanding!

I was wondering why the CONTRIBUTING.md file at the root of the codebase was not just one sentence linking to the online docs; the reason is that this way, a contributor can clone the repository and have all the information locally, without having to click many links to get the right information.

I'll go ahead and close this issue.
