### ISSUE TITLE
tech design of train test split assist

### ISSUE THREAD

**Issue by MarieSacksick** [probabl-ai/skore#668]
Create tech design of how to implement the train test split new functionality.  

- How should warning be displayed?
- How should warning objects live?

Following these decisions, create sub-steps of development.

**Comment by tuscland** [comment]
This issue is about defining technical requirements and designing the implementation of the feature described in the parent epic. 

> - How should warning be displayed?

This is specified in the parent epic: warnings should be picked-up by the user's IDE (Jupyter or VS Code). It seems that the standard Python library `warnings` could fit the requirements, but some exploration is needed to be sure.

> - How should warning objects live?

In the current version of this feature, warnings are transient, that is, they are emitted and not persisted.

Future developments might consist of meshing Items, warnings, and information about function calls (stacktrace, line of code, environment, etc.) in order to give the user as much context as possible, and different ways of navigating the information.

**Comment by augustebaum** [comment]
The goal of this issue is to write issues; this feels a bit strange to me ^^'

**Comment by MarieS-WiMLDS** [comment]
Most of this issue should be about documenting options, maybe doing some tech mvp tests, and taking a decision hopefully; creating an issue for actual implementation will be the last short step.  
The goal of having one issue for tech design and one for implementation is to avoid having plenty of comments stating plenty of options (which is cool!), and when going to implementation step, it's difficult to navigate through all that has been said. also, when not split, the issue is blocked in design, and it looks like it's not something we are currently working on.

**Comment by augustebaum** [comment]
Now that #683 and #684 have been opened, I'm thinking this can be closed
