### ISSUE TITLE
New view name should increment

### ISSUE THREAD

**Issue by MarieS-WiMLDS** [probabl-ai/skore#708]
### Is your feature request related to a problem? Please describe.

It should be possible imo to create several views without having to name them.   
Currently the situation is this one:  
![image](https://github.com/user-attachments/assets/2f6f36cd-a6d9-48be-b004-a308b81e76ee)

### Describe the solution you'd like

New view _iterative number_?  

### Describe alternatives you've considered, if relevant

New new view, new new new view etc, but this seems very bad practice :) !

**Comment by rouk1** [comment]
Actually we tried to achieve a UX where you can only have one pending rename view. Hence if you chose to keep the new view name then the next view you'll create cant be named "new view" and you'll have a error toast.
The idea was to force user to give good names and not keep the placeholder name.

We can do a check if there is a "new view" named view actually then add a + 1 to it but then how would that scale ? Should we do regex capture of the number ?

**Comment by tuscland** [comment]
What I did in a past software was to have:

- "New view"
- "New view 1"
- "New view 2"
… Incrementing an integer that is parsed at the end of the last name (which first involved ordering the list in descending natural order in order to find the last one).

I think it is the best compromise: at the moment, we don't believe there are strict requirements on view naming, and after it's the responsibility of the user to name it as they see fit.
