### ISSUE TITLE
Use polars instead in examples

### ISSUE THREAD

**Issue by adrinjalali** [probabl-ai/skore#712]
Modern examples at this point should be using `polars` instead really, instead of `pandas`. For instance, here: https://github.com/probabl-ai/skore/blob/main/examples/plot_01_getting_started.py

**Comment by thomass-dev** [comment]
I have nothing against, but what are the cons of using `pandas` in the example notebooks? Can we use both instead?

**Comment by adrinjalali** [comment]
At this point using polars on new code just seems old school since when starting a new project, we'd recommend users to start with polars anyway. It has better API and is faster, and narwhals basically mirrors its API.

**Comment by thomass-dev** [comment]
> At this point using polars on new code just seems old school

*pandas, right?

For a better adoption, i would recommend to put example of both `pandas` and `polars`, and add a comment to recommend `polars`.

**Comment by tuscland** [comment]
Let's keep it simple and just focus on polars as Adrin suggested.

**Comment by sylvaincom** [comment]
I'm trying to do a `put` of a polars dataframe but it does not work, I get we do not support polars yet? cc @augustebaum

**Comment by thomass-dev** [comment]
No polars is not supported yet.

**Comment by tuscland** [comment]
Waiting for polars support via #758.

**Comment by sylvaincom** [comment]
As of today, pandas seems to be more popular than polars with regards to usage (number of downloads per month, etc).

Moreover, polars seems better than pandas mainly because its computations are faster. But in skore project, we don't really recommend storing large data frames. And in the getting started example, the data frame is just a toy one.

Hence, adding polars dataframe in the [Overview of the skore project](https://probabl-ai.github.io/skore/latest/auto_examples/plot_02_overview_skore_project.html) example (in addition to pandas), but keeping pandas only in the [Getting started with skore](https://probabl-ai.github.io/skore/latest/auto_examples/plot_01_getting_started.html) example seems like a good compromise? WDYT? I don't have a strong opinion on this.
