### ISSUE TITLE
Entry point for CLI

### ISSUE THREAD

**Issue by adrinjalali** [probabl-ai/skore#717]
We need to declare the right "entry points" for our CLI, so that there's not need to write `python3 -m skore ...`

ref: https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#advanced-plugins

And then the commands become:

```sh
skore launch "my_project"
```

instead of 

```sh
python -m skore launch "my_project"
```

cc @glemaitre

**Comment by thomass-dev** [comment]
Actually, it was a voluntary choice to use `skore` as a callable package instead of an entry-point.
It has the advantage of not hiding that these commands come from the python package, and of avoiding problems in editable mode.

What's your feeling about this user API @MarieS-WiMLDS?

**Comment by MarieS-WiMLDS** [comment]
From a user point of view, this proposed version is much smoother, I like it.  
What do you call "editable mode"? what kind of problem we could run into?

**Comment by glemaitre** [comment]
I'm interesting to know what is the issue regarding the editable mode?

I'm currently using `pixi` where `skore` is installed in editable mode (cf. https://github.com/glemaitre/scikit-learn-workspace/blob/main/src/skore/pixi.toml) and I don't witness any issue.

@thomass-dev is it related that making changes in the `cli.py` would not have effect immediately because you would need a `pip install`? (I don't witness this issue because `pixi` would rerun automatically the `pip` install the environment activation).
